/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShaderImport } from './routes/shader'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ShaderRoute = ShaderImport.update({
  id: '/shader',
  path: '/shader',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/shader': {
      id: '/shader'
      path: '/shader'
      fullPath: '/shader'
      preLoaderRoute: typeof ShaderImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shader': typeof ShaderRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shader': typeof ShaderRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/shader': typeof ShaderRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shader'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shader'
  id: '__root__' | '/' | '/shader'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShaderRoute: typeof ShaderRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShaderRoute: ShaderRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/shader"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/shader": {
      "filePath": "shader.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
